syntax = "proto3";

package pb;

option go_package = "./github.com/MOHANKUMAR-IT/go-libp2p-netsync/pb";

service NetSyncService {
  rpc ServiceRequest(NetSyncMessage) returns (NetSyncMessage);
}

message NetSyncMessage {
  string key = 1;
  string peerid = 2;
  LockState lock_state = 4;
}

enum LockState {
  LOCK_INVALID = 0;
  LOCK_TRY_ACQUIRE = 1;
  LOCK_TRY_RS_ACQUIRE = 2;
  LOCK_TRY_RELEASE = 3;
  LOCK_ACQUIRED = 4;
  LOCK_ACQUIRE_FAILED = 5;
  LOCK_RELEASED = 6;
  LOCK_RELEASE_FAILED = 7;
}
