// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: msg.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetSyncService_ServiceRequest_FullMethodName = "/pb.NetSyncService/ServiceRequest"
)

// NetSyncServiceClient is the client API for NetSyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetSyncServiceClient interface {
	ServiceRequest(ctx context.Context, in *NetSyncMessage, opts ...grpc.CallOption) (*NetSyncMessage, error)
}

type netSyncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNetSyncServiceClient(cc grpc.ClientConnInterface) NetSyncServiceClient {
	return &netSyncServiceClient{cc}
}

func (c *netSyncServiceClient) ServiceRequest(ctx context.Context, in *NetSyncMessage, opts ...grpc.CallOption) (*NetSyncMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetSyncMessage)
	err := c.cc.Invoke(ctx, NetSyncService_ServiceRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetSyncServiceServer is the server API for NetSyncService service.
// All implementations must embed UnimplementedNetSyncServiceServer
// for forward compatibility.
type NetSyncServiceServer interface {
	ServiceRequest(context.Context, *NetSyncMessage) (*NetSyncMessage, error)
	mustEmbedUnimplementedNetSyncServiceServer()
}

// UnimplementedNetSyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetSyncServiceServer struct{}

func (UnimplementedNetSyncServiceServer) ServiceRequest(context.Context, *NetSyncMessage) (*NetSyncMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServiceRequest not implemented")
}
func (UnimplementedNetSyncServiceServer) mustEmbedUnimplementedNetSyncServiceServer() {}
func (UnimplementedNetSyncServiceServer) testEmbeddedByValue()                        {}

// UnsafeNetSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetSyncServiceServer will
// result in compilation errors.
type UnsafeNetSyncServiceServer interface {
	mustEmbedUnimplementedNetSyncServiceServer()
}

func RegisterNetSyncServiceServer(s grpc.ServiceRegistrar, srv NetSyncServiceServer) {
	// If the following call pancis, it indicates UnimplementedNetSyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetSyncService_ServiceDesc, srv)
}

func _NetSyncService_ServiceRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetSyncMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetSyncServiceServer).ServiceRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetSyncService_ServiceRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetSyncServiceServer).ServiceRequest(ctx, req.(*NetSyncMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// NetSyncService_ServiceDesc is the grpc.ServiceDesc for NetSyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetSyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.NetSyncService",
	HandlerType: (*NetSyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServiceRequest",
			Handler:    _NetSyncService_ServiceRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "msg.proto",
}
